name: Social Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: zylele/social-readme@master
        with:
          blog_rss_link: https://www.zuozuovera.com/feed/
          blog_limit: 5 # blog数量
          douban_name: {test}
          douban_limit: 5 # 豆瓣最新动态数量
          commit_message: Updated social rss by social-readme # commit说明